# Generated by Django 5.1.6 on 2025-03-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_whattoreadarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='skiped',
        ),
    ]
